# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

email: your-email@domain.com
description: My site description (for SEO)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

# Custom vars
theme_color: "#0066cc"
css_theme: t-Pac
owner: AgID
owner_desc: Agenzia per l'Italia Digitale
logo: http://designer.italia.it/images/loghi/logo-it.svg
owner_logo: https://www.spid.gov.it/assets/img/agid-logo-bb.svg

collections:
   pages:
     output: true
     permalink: /:path/
     layout: page
   projects:
     output: true
     permalink: /:path/
     layout: project
   faqs:
     output: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      subnav: "subnav"
