it:
  code: ita
  name: italiano
  t:
    desc: sito in italiano
    active_lang: lingua attiva
en:
  code: eng
  name: english
  t:
    desc: website in english
    active_lang: current language
de:
  code: deu
  name: deutsch
  t:
    desc: website in english
    active_lang: current language
es:
  code: esp
  name: español
  t:
    desc: website in english
    active_lang: current language
